testing refactor

diff --git a/cicd/buildspec-ci.yml b/cicd/buildspec-ci.yml
--- a/cicd/buildspec-ci.yml
+++ b/cicd/buildspec-ci.yml
@@ -1,3 +1,21 @@
+######################################################################
+#  Developer Portal CodeBuild CI
+#  
+#
+# Tool Links:
+#  - CodeBuild - https://docs.aws.amazon.com/codebuild/index.html
+#  - Runner for CodeBuild Enironment - https://github.com/department-of-veterans-affairs/lighthouse-codebuild-containers/tree/main/docker-runner
+#  - AWS CLI 2.0 - https://docs.aws.amazon.com/cli/latest/userguide/cli-chap-welcome.html
+# 
+# All Custom scripts are on the CodeBuild Environment container. 
+# https://github.com/department-of-veterans-affairs/lighthouse-codebuild-containers/tree/main/
+#
+# Custom Scripts:
+#  - prnum.sh
+#  - prcomment.sh
+#  - slackpost.sh
+#
+######################################################################
 version: 0.2
 env:
   variables:
@@ -18,6 +36,7 @@ env:
     PREVIEW_SENTRY_DSN: "http://dc7d5ebec20e474c80f8150c399d2955@sentry.vfs.va.gov/26"
     # Setting REPO
     REPO: "department-of-veterans-affairs/developer-portal"
+    # Running the container as root.
     UNAME: root
     GNAME: root
   parameter-store:
@@ -35,8 +54,11 @@ phases:
       # set variables
       # Bypass tests if a PR is created
       - if [[ $CODEBUILD_WEBHOOK_EVENT == "PULL_REQUEST_CREATED"  ]]; then TESTS=""; fi
+      # Log all environment varbiables to cloudwatch incase we need to troubleshoot
+      - printenv
+      # Get usable branch name
       - GET_BRANCH=${CODEBUILD_WEBHOOK_HEAD_REF#"refs/heads/"}
-      # set branch
+      # set branch if not set from Webhook
       - |
         if [[ $BRANCH ]]; then
           echo branch set as -- ${BRANCH} -- from console
@@ -64,8 +86,6 @@ phases:
           done
         fi
       - make build
-      - mkdir -p test/image_snapshots/__diff_output__
-      - mkdir -p reports
   build:
     # We use a phase variable to tell where we are in case of failure. This will allow us to handle the POST_BUILD stage with (some) grace.
     commands:
@@ -80,20 +100,22 @@ phases:
           make ${test} || break
           phase=test_success
         done
-      - if [[ ${phase} != "test_success" ]]; then exit 1; fi
+      - if [[ ${phase} != "test_success"  && ${phase} != "test" ]]; then exit 1; fi
       # Run builds if all tests are good. We run all builds but we could shorten the CI part for branches by only building on push.
       - phase=build_app
       - |
         for env in ${ENVS}; do
-          make build_app ENV=${env} || exit 1
+      # CodeBuild sometimes ignores make exit codes.
+          make build_app ENV=${env} || exit 1 
         done
       # Check if we archive the build
       - phase=archive
       - |
         if [[ $BRANCH == 'master' ]]; then
           for env in ${ENVS}; do
-            make archive ENV=${env} || exit 1
-            aws s3 cp --no-progress --acl public-read ${env}.tar.bz2 s3://${S3_ARCHIVE_BUCKET}/cb-${COMMIT_HASH}/${env}.tar.bz2
+      # CodeBuild sometimes ignores make exit codes.
+            make archive ENV=${env} || exit 1 
+            aws s3 cp --no-progress --acl public-read build/${env}.tar.bz2 s3://${S3_ARCHIVE_BUCKET}/cb-${COMMIT_HASH}/${env}.tar.bz2
           done
         fi
       # Check if we deploy to the review bucket
@@ -102,7 +124,6 @@ phases:
         if [[ ${PR_NUM} ]]; then
           links=""
           for env in ${ENVS}; do
-            mv ${env} build
             links="${links}[${env}](https://s3-us-gov-west-1.amazonaws.com/${S3_REVIEW_BUCKET}/${S3_BRANCH}/${COMMIT_HASH}/${env}/index.html) <br>"
           done
           aws s3 sync --no-progress --acl public-read build/ s3://${S3_REVIEW_BUCKET}/${S3_BRANCH}/${COMMIT_HASH}/
@@ -115,16 +136,18 @@ phases:
       - |
         case ${phase} in
         visual) 
+          report_path="test/image_snapshots/diff_output/"
           links=""
-          for f in reports/*; do
-            links="${links}[${f#"reports/"}](https://s3-us-gov-west-1.amazonaws.com/${S3_VISUAL_BUCKET}/${S3_BRANCH}/${COMMIT_HASH}/${f#"reports/"})"
+          for f in ${report_path}/*; do
+            links="${links}[${f#"${report_path}"}](https://s3-us-gov-west-1.amazonaws.com/${S3_VISUAL_BUCKET}/${S3_BRANCH}/${COMMIT_HASH}/${f#"${report_path}"})"
           done
-          aws s3 sync --no-progress reports/ s3://${S3_VISUAL_BUCKET}/${S3_BRANCH}/${COMMIT_HASH}/
+          aws s3 sync --no-progress ${reports_path} s3://${S3_VISUAL_BUCKET}/${S3_BRANCH}/${COMMIT_HASH}/
           docsLink="https://github.com/${REPO}/blob/master/docs/testing.md#visual-regression-testing"
           comment="Visual regression testing failed. Review these diffs and then [update the snapshots](${docsLink}). <br><br> ${links}"
           ;;
         unit|lint|security|e2e|accessibility)
-          aws s3 sync --no-progress reports/ s3://${S3_ERROR_BUCKET}/${S3_BRANCH}/${COMMIT_HASH}/
+          if [[ $phase == "lint" ]]; then report=lint-results.xml; else report=test-report.xml; fi
+          aws s3 cp --no-progress ${report} s3://${S3_ERROR_BUCKET}/${S3_BRANCH}/${COMMIT_HASH}/
           link="[report](https://console.amazonaws-us-gov.com/s3/buckets/${S3_ERROR_BUCKET}/${S3_BRANCH}/${COMMIT_HASH}/)"
           comment="There was an error during the ${phase} test. View your ${link} for more information."
           ;;
